version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    environment:
      - sygua_DB__uri=postgresql://postgres:postgres@db:5432/sygua
      - sygua_DB__connect_args={}
    volumes:
      - .:/home/app/web
    depends_on:
      - db
  db:
    build: postgres
    image: sygua_postgres-13-alpine-multi-user
    volumes:
      - $HOME/.postgres/sygua_db/data/postgresql:/var/lib/postgresql/data
    ports:
      - 5435:5432
    environment:
      - POSTGRES_DBS=sygua, sygua_test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
